### ISSUE TITLE
Missing filenames 

### ISSUE THREAD

**Issue by SciLor** [mon/cc3200tool#3]
I am using tonieboxes with a 4kB flash chip. With cc3200tool on nost of the boxes it is possible to get the list_filesystem.
Some boxes (all are working as expected in normal use) have problems reading the file list.

If I read the flash with list_filesystem a file list is shown. But the file names are missing. If you delete the file and rewrite a file the filename ist shown for just this file.

Currently I have no direct access to such a box. If I got one, I add more info.
(I am searching for a screenshot I have got)

**Comment by mon** [comment]
We have this problem all the time, it's a fundamental issue with how the CC3200 filesystem deals with files. In some cases the filename is lost/corrupted, despite the contents being safe. I believe the NWP internally hashes the filename, which is why you can still read/write/delete if you know the filename, but bruteforcing is not possible.

Unfortunately there's not much you can do except map the unknown files by testing known filenames.

Feel free to reopen this issue if you want me to find the TI employee's forum post confirming this as known behaviour.

**Comment by SciLor** [comment]
It would be nice to have the documentation about the problem right here for the future.

**Comment by mon** [comment]
[Here's the forum post](https://e2e.ti.com/support/wireless-connectivity/wifi/f/968/p/512435/1866027#1866027)

If that ever goes down, the note from the TI employee:

> The *** marking is a known issue that may happen under certain conditions like the following:
> 
>     Create a file, write some data and don’t close it
>     Reset the device
>     Create the same file again (you cannot erase it, you must create), write some data and now close it
>     All filenames would appear as *********** but the files are there in the file system and it should work OK
> 
> However, like you stated, the actual files in the filesystem are not affected by this.
> 
> If you still need to see files listed, the current workaround for this is to make sure you write all files in one session.
